### ISSUE TITLE
Fatal error when activating plugin

### ISSUE THREAD

**Issue by gareth94** [LearnPress/learnpress#550]
Hello. I'm quite new to GitHub so please excuse my lack of knowledge! I've just downloaded the plugin by going to Code => Download Zip. However when I upload and activate the plugin on my site I get the error below. Please can you help? 

```
Warning: require_once(/home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/vendor/autoload.php): Failed to open stream: No such file or directory in /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php on line 210

Fatal error: Uncaught Error: Failed opening required '/home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/vendor/autoload.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php:210 Stack trace: #0 /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php(161): LearnPress->includes() #1 /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php(887): LearnPress->__construct() #2 /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php(929): LearnPress::instance() #3 /home/ceaadaa3/mysite.com/wp-admin/includes/plugin.php(2314): include_once('/home/ceaadaa3/...') #4 /home/ceaadaa3/mysite.com/wp-admin/plugins.php(192): plugin_sandbox_scrape() #5 {main} thrown in /home/ceaadaa3/mysite.com/wp-content/plugins/learnpress-develop/learnpress.php on line 210 
```

**Comment by tungnxt89** [comment]
Hi gareth94,

You need to install [Composer ](https://getcomposer.org/) and run the command: "composer install" or "composer update" if run "composer install" before.

Thaks.

**Comment by tungnxt89** [comment]
Hi gareth94,

Because you don't build JS and CSS. You need to read the guide on the https://github.com/LearnPress/learnpress#for-developer

Thanks.
